name: "Make and tests"
description: "Make, unittest & integration test"

inputs:
  exercise:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Сборка
      shell: bash
      run: |
        pushd "${{ inputs.exercise }}"
        make depends
        make release
        make debug
        make debug_test
        popd

    - name: Модульные тесты
      shell: bash
      run: |
        pushd "${{ inputs.exercise }}"
        make run_debug_test
        popd
